version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - STORAGE_PATH=/data
    volumes:
      - ./src/workweek_survey:/app/src/workweek_survey
      - ./data:/data
    command: uvicorn workweek_survey.main:app --reload --host 0.0.0.0 --port 8000
