version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./src/workweek_survey:/app/src/workweek_survey
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn workweek_survey.main:app --reload --host 0.0.0.0 --port ${PORT}
